/*
Copyright 2019 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSyncRepos implements SyncRepoInterface
type FakeSyncRepos struct {
	Fake *FakeTriggersV1alpha1
	ns   string
}

var syncreposResource = schema.GroupVersionResource{Group: "triggers.tekton.dev", Version: "v1alpha1", Resource: "syncrepos"}

var syncreposKind = schema.GroupVersionKind{Group: "triggers.tekton.dev", Version: "v1alpha1", Kind: "SyncRepo"}

// Get takes name of the syncRepo, and returns the corresponding syncRepo object, and an error if there is any.
func (c *FakeSyncRepos) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SyncRepo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(syncreposResource, c.ns, name), &v1alpha1.SyncRepo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SyncRepo), err
}

// List takes label and field selectors, and returns the list of SyncRepos that match those selectors.
func (c *FakeSyncRepos) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SyncRepoList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(syncreposResource, syncreposKind, c.ns, opts), &v1alpha1.SyncRepoList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SyncRepoList{ListMeta: obj.(*v1alpha1.SyncRepoList).ListMeta}
	for _, item := range obj.(*v1alpha1.SyncRepoList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested syncRepos.
func (c *FakeSyncRepos) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(syncreposResource, c.ns, opts))

}

// Create takes the representation of a syncRepo and creates it.  Returns the server's representation of the syncRepo, and an error, if there is any.
func (c *FakeSyncRepos) Create(ctx context.Context, syncRepo *v1alpha1.SyncRepo, opts v1.CreateOptions) (result *v1alpha1.SyncRepo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(syncreposResource, c.ns, syncRepo), &v1alpha1.SyncRepo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SyncRepo), err
}

// Update takes the representation of a syncRepo and updates it. Returns the server's representation of the syncRepo, and an error, if there is any.
func (c *FakeSyncRepos) Update(ctx context.Context, syncRepo *v1alpha1.SyncRepo, opts v1.UpdateOptions) (result *v1alpha1.SyncRepo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(syncreposResource, c.ns, syncRepo), &v1alpha1.SyncRepo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SyncRepo), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSyncRepos) UpdateStatus(ctx context.Context, syncRepo *v1alpha1.SyncRepo, opts v1.UpdateOptions) (*v1alpha1.SyncRepo, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(syncreposResource, "status", c.ns, syncRepo), &v1alpha1.SyncRepo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SyncRepo), err
}

// Delete takes name of the syncRepo and deletes it. Returns an error if one occurs.
func (c *FakeSyncRepos) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(syncreposResource, c.ns, name), &v1alpha1.SyncRepo{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSyncRepos) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(syncreposResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SyncRepoList{})
	return err
}

// Patch applies the patch and returns the patched syncRepo.
func (c *FakeSyncRepos) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SyncRepo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(syncreposResource, c.ns, name, pt, data, subresources...), &v1alpha1.SyncRepo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SyncRepo), err
}
